version: "3.8"
services:
    db:
        image: mysql:8.0.19
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: asdfg
            MYSQL_PASSWORD: asdfg
        ports:
          - "3308:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"
